<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C48_Folha.txt.seg | D2_C48_Estadao.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C48_Folha.txt.seg | D2_C48_Estadao.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE NMTOKEN #FIXED "todos" >
<!ATTLIST RELATION TYPE NMTOKEN #REQUIRED >
] > 
<Anotation>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="1" TDID="D2_C48_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="2" TDID="D2_C48_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D2_C48_Estadao.txt.seg" SSENT="14" TDID="D1_C48_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="4" TDID="D2_C48_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Equivalence" JUDGE="todos"/>
	</R>
	<R SDID="D2_C48_Estadao.txt.seg" SSENT="6" TDID="D1_C48_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="5" TDID="D2_C48_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="7" TDID="D2_C48_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D2_C48_Estadao.txt.seg" SSENT="16" TDID="D1_C48_Folha.txt.seg" TSENT="8">
		<RELATION TYPE="Subsumption" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="11" TDID="D2_C48_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Contradiction" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="11" TDID="D2_C48_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="todos"/>
	</R>
	<R SDID="D1_C48_Folha.txt.seg" SSENT="16" TDID="D2_C48_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D2_C48_Estadao.txt.seg" SSENT="11" TDID="D1_C48_Folha.txt.seg" TSENT="16">
		<RELATION TYPE="Elaboration" JUDGE="todos"/>
	</R>
</Anotation>
