<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C4_Folha.txt.seg | D2_C4_Estadao.txt.seg | D3_C4_OGlobo.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT ( 1 | 12 | 17 | 2 | 3 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >
<!ATTLIST R TDID ( D1_C4_Folha.txt.seg | D2_C4_Estadao.txt.seg | D3_C4_OGlobo.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 10 | 11 | 12 | 16 | 18 | 2 | 3 | 4 | 5 | 6 | 9 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia_Vinicius | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Attribution | Contradiction | Elaboration | Follow-up | Historical-background | Modality | Overlap ) #REQUIRED >
] > 
<Anotation>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="1" TDID="D2_C4_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="1" TDID="D2_C4_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="1" TDID="D2_C4_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="2" TDID="D2_C4_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="3" TDID="D1_C4_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="6" TDID="D1_C4_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="3" TDID="D2_C4_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Contradiction" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="2" TDID="D1_C4_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Attribution" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="5" TDID="D2_C4_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="5" TDID="D2_C4_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="5" TDID="D2_C4_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="6" TDID="D2_C4_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="7" TDID="D2_C4_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="7" TDID="D2_C4_Estadao.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="7" TDID="D2_C4_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="7" TDID="D2_C4_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="1" TDID="D1_C4_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="9" TDID="D2_C4_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="2" TDID="D1_C4_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="1" TDID="D3_C4_OGlobo.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="12" TDID="D1_C4_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Modality" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="1" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="11">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="17" TDID="D1_C4_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="3" TDID="D3_C4_OGlobo.txt.seg" TSENT="11">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="3" TDID="D3_C4_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="17" TDID="D1_C4_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="3" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="5" TDID="D3_C4_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="5" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="7" TDID="D3_C4_OGlobo.txt.seg" TSENT="12">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="8" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="9" TDID="D3_C4_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C4_Folha.txt.seg" SSENT="9" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="1" TDID="D3_C4_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="3" TDID="D2_C4_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="1" TDID="D3_C4_OGlobo.txt.seg" TSENT="9">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="1" TDID="D3_C4_OGlobo.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="17" TDID="D2_C4_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="2" TDID="D3_C4_OGlobo.txt.seg" TSENT="18">
		<RELATION TYPE="Contradiction" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C4_Estadao.txt.seg" SSENT="3" TDID="D3_C4_OGlobo.txt.seg" TSENT="12">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="12" TDID="D2_C4_Estadao.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C4_OGlobo.txt.seg" SSENT="12" TDID="D2_C4_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
</Anotation>
