<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID NMTOKEN #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID NMTOKEN #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE NMTOKEN #FIXED "todos" >
<!ATTLIST RELATION TYPE NMTOKEN #REQUIRED >

] > 
<Anotation>
	<R SDID="D1_C23_Folha.txt.seg" SSENT="1" TDID="D2_C23_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="todos"/>
	</R>
	<R SDID="D2_C23_Estadao.txt.seg" SSENT="1" TDID="D1_C23_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Attribution" JUDGE="todos"/>
	</R>
	<R SDID="D2_C23_Estadao.txt.seg" SSENT="2" TDID="D1_C23_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="todos"/>
	</R>
	<R SDID="D2_C23_Estadao.txt.seg" SSENT="6" TDID="D1_C23_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="todos"/>
	</R>
	<R SDID="D2_C23_Estadao.txt.seg" SSENT="4" TDID="D1_C23_Folha.txt.seg" TSENT="7">
		<RELATION TYPE="Elaboration" JUDGE="todos"/>
	</R>
	<R SDID="D1_C23_Folha.txt.seg" SSENT="10" TDID="D2_C23_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Historical-background" JUDGE="todos"/>
	</R>
	<R SDID="D1_C23_Folha.txt.seg" SSENT="10" TDID="D2_C23_Estadao.txt.seg" TSENT="13">
		<RELATION TYPE="Historical-background" JUDGE="todos"/>
	</R>
	<R SDID="D1_C23_Folha.txt.seg" SSENT="11" TDID="D2_C23_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="todos"/>
	</R>
</Anotation>
