<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C3_Folha.txt.seg | D2_C3_Estadao.txt.seg | D3_C3_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C3_Folha.txt.seg | D2_C3_Estadao.txt.seg | D3_C3_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 15 | 18 | 2 | 25 | 4 | 5 | 6 | 7 | 8 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Attribution | Contradiction | Elaboration | Equivalence | Follow-up | Historical-background | Overlap | Subsumption ) #REQUIRED >

] > 
<Anotation>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="1" TDID="D2_C3_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="7" TDID="D1_C3_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="6" TDID="D2_C3_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="6" TDID="D2_C3_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="6" TDID="D2_C3_Estadao.txt.seg" TSENT="7">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="15" TDID="D2_C3_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="15" TDID="D2_C3_Estadao.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="17" TDID="D2_C3_Estadao.txt.seg" TSENT="8">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="8" TDID="D1_C3_Folha.txt.seg" TSENT="18">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="19" TDID="D2_C3_Estadao.txt.seg" TSENT="8">
		<RELATION TYPE="Contradiction" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="7" TDID="D1_C3_Folha.txt.seg" TSENT="25">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C3_JB.txt.seg" SSENT="1" TDID="D1_C3_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Attribution" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="1" TDID="D3_C3_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="1" TDID="D3_C3_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C3_JB.txt.seg" SSENT="5" TDID="D1_C3_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="1" TDID="D3_C3_JB.txt.seg" TSENT="15">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="2" TDID="D3_C3_JB.txt.seg" TSENT="15">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="5" TDID="D3_C3_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="5" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="6" TDID="D3_C3_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Equivalence" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="11" TDID="D3_C3_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="11" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="11" TDID="D3_C3_JB.txt.seg" TSENT="15">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="13" TDID="D3_C3_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="13" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Historical-background" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C3_JB.txt.seg" SSENT="2" TDID="D1_C3_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="15" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="17" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C3_Folha.txt.seg" SSENT="19" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="2" TDID="D3_C3_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="2" TDID="D3_C3_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="4" TDID="D3_C3_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C3_Estadao.txt.seg" SSENT="7" TDID="D3_C3_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C3_JB.txt.seg" SSENT="5" TDID="D2_C3_Estadao.txt.seg" TSENT="7">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C3_JB.txt.seg" SSENT="5" TDID="D2_C3_Estadao.txt.seg" TSENT="8">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
</Anotation>
