<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C29_Folha.txt.seg | D2_C29_OGlobo.txt.seg | D3_C29_GPovo.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT ( 1 | 10 | 11 | 12 | 13 | 14 | 17 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >
<!ATTLIST R TDID ( D1_C29_Folha.txt.seg | D2_C29_OGlobo.txt.seg | D3_C29_GPovo.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 10 | 11 | 12 | 13 | 14 | 19 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Elaboration | Follow-up | Historical-background | Identity | Overlap | Subsumption ) #REQUIRED >
] > 
<Anotation>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="1" TDID="D2_C29_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="11" TDID="D1_C29_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="2" TDID="D1_C29_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="9" TDID="D1_C29_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="12" TDID="D1_C29_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="4" TDID="D2_C29_OGlobo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="2" TDID="D1_C29_Folha.txt.seg" TSENT="8">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="14" TDID="D1_C29_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="1" TDID="D1_C29_Folha.txt.seg" TSENT="11">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="3" TDID="D1_C29_Folha.txt.seg" TSENT="11">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="13" TDID="D2_C29_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="3" TDID="D1_C29_Folha.txt.seg" TSENT="13">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="13" TDID="D2_C29_OGlobo.txt.seg" TSENT="13">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="13" TDID="D2_C29_OGlobo.txt.seg" TSENT="14">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="4" TDID="D1_C29_Folha.txt.seg" TSENT="14">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="17" TDID="D2_C29_OGlobo.txt.seg" TSENT="11">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="11" TDID="D1_C29_Folha.txt.seg" TSENT="19">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="1" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="11" TDID="D1_C29_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="2" TDID="D3_C29_GPovo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="9" TDID="D1_C29_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="10" TDID="D1_C29_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="4" TDID="D3_C29_GPovo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="5" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="14" TDID="D1_C29_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="11" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="11" TDID="D3_C29_GPovo.txt.seg" TSENT="3">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="13" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="13" TDID="D3_C29_GPovo.txt.seg" TSENT="3">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="13" TDID="D3_C29_GPovo.txt.seg" TSENT="13">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="14" TDID="D1_C29_Folha.txt.seg" TSENT="13">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="14" TDID="D3_C29_GPovo.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C29_Folha.txt.seg" SSENT="17" TDID="D3_C29_GPovo.txt.seg" TSENT="11">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="11" TDID="D1_C29_Folha.txt.seg" TSENT="19">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="1" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="3" TDID="D2_C29_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C29_GPovo.txt.seg" SSENT="14" TDID="D2_C29_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="2" TDID="D3_C29_GPovo.txt.seg" TSENT="2">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="3" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="3" TDID="D3_C29_GPovo.txt.seg" TSENT="3">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="4" TDID="D3_C29_GPovo.txt.seg" TSENT="4">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="5" TDID="D3_C29_GPovo.txt.seg" TSENT="5">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="6" TDID="D3_C29_GPovo.txt.seg" TSENT="6">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="7" TDID="D3_C29_GPovo.txt.seg" TSENT="7">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="8" TDID="D3_C29_GPovo.txt.seg" TSENT="8">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="9" TDID="D3_C29_GPovo.txt.seg" TSENT="9">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="10" TDID="D3_C29_GPovo.txt.seg" TSENT="10">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="11" TDID="D3_C29_GPovo.txt.seg" TSENT="11">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="12" TDID="D3_C29_GPovo.txt.seg" TSENT="12">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="13" TDID="D3_C29_GPovo.txt.seg" TSENT="13">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="14" TDID="D3_C29_GPovo.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C29_OGlobo.txt.seg" SSENT="14" TDID="D3_C29_GPovo.txt.seg" TSENT="14">
		<RELATION TYPE="Identity" JUDGE="Lucia"/>
	</R>
</Anotation>
