<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C2_Folha.txt.seg | D2_C2_Estadao.txt.seg | D4_C2_Globo.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT ( 1 | 10 | 11 | 12 | 13 | 15 | 16 | 17 | 18 | 2 | 21 | 3 | 4 | 5 | 6 | 8 | 9 ) #REQUIRED >
<!ATTLIST R TDID ( D1_C2_Folha.txt.seg | D2_C2_Estadao.txt.seg | D4_C2_Globo.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 10 | 11 | 13 | 14 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia_Vinicius | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Attribution | Contradiction | Elaboration | Equivalence | Follow-up | Overlap | Subsumption ) #REQUIRED >
] > 

<Anotation>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="1" TDID="D1_C2_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="8" TDID="D1_C2_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="18" TDID="D1_C2_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="2" TDID="D2_C2_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="2" TDID="D2_C2_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="10" TDID="D1_C2_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="16" TDID="D1_C2_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="3" TDID="D1_C2_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="17" TDID="D1_C2_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="5" TDID="D1_C2_Folha.txt.seg" TSENT="5">
		<RELATION TYPE="Attribution" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="5" TDID="D2_C2_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="1" TDID="D1_C2_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="9" TDID="D2_C2_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="8" TDID="D1_C2_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="8" TDID="D1_C2_Folha.txt.seg" TSENT="10">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="10" TDID="D1_C2_Folha.txt.seg" TSENT="11">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="12" TDID="D2_C2_Estadao.txt.seg" TSENT="10">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="13" TDID="D2_C2_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="10" TDID="D1_C2_Folha.txt.seg" TSENT="13">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="11" TDID="D1_C2_Folha.txt.seg" TSENT="13">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="21" TDID="D1_C2_Folha.txt.seg" TSENT="14">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="15" TDID="D2_C2_Estadao.txt.seg" TSENT="4">
		<RELATION TYPE="Equivalence" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="17" TDID="D2_C2_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="18" TDID="D2_C2_Estadao.txt.seg" TSENT="8">
		<RELATION TYPE="Contradiction" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="1" TDID="D4_C2_Globo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="1" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="2" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="2" TDID="D4_C2_Globo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="3" TDID="D4_C2_Globo.txt.seg" TSENT="4">
		<RELATION TYPE="Contradiction" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="4" TDID="D4_C2_Globo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="4" TDID="D4_C2_Globo.txt.seg" TSENT="6">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="5" TDID="D4_C2_Globo.txt.seg" TSENT="8">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D4_C2_Globo.txt.seg" SSENT="2" TDID="D1_C2_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="11" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="12" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="15" TDID="D4_C2_Globo.txt.seg" TSENT="6">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="16" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C2_Folha.txt.seg" SSENT="16" TDID="D4_C2_Globo.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="1" TDID="D4_C2_Globo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="1" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C2_Globo.txt.seg" SSENT="2" TDID="D2_C2_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="3" TDID="D4_C2_Globo.txt.seg" TSENT="3">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="3" TDID="D4_C2_Globo.txt.seg" TSENT="4">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C2_Globo.txt.seg" SSENT="6" TDID="D2_C2_Estadao.txt.seg" TSENT="4">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="5" TDID="D4_C2_Globo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="5" TDID="D4_C2_Globo.txt.seg" TSENT="8">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C2_Globo.txt.seg" SSENT="2" TDID="D2_C2_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="8" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="9" TDID="D4_C2_Globo.txt.seg" TSENT="7">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="10" TDID="D4_C2_Globo.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="12" TDID="D4_C2_Globo.txt.seg" TSENT="7">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="13" TDID="D4_C2_Globo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="16" TDID="D4_C2_Globo.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="17" TDID="D4_C2_Globo.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="18" TDID="D4_C2_Globo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C2_Estadao.txt.seg" SSENT="21" TDID="D4_C2_Globo.txt.seg" TSENT="8">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
</Anotation>
