<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C17_Folha.txt.seg | D2_C17_Estadao.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C17_Folha.txt.seg | D2_C17_Estadao.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE NMTOKEN #FIXED "Vinicius" >
<!ATTLIST RELATION TYPE ( Elaboration | Equivalence | Follow-up | Overlap | Subsumption ) #REQUIRED >
] > 
<Anotation>
	<R SDID="D2_C17_Estadao.txt.seg" SSENT="1" TDID="D1_C17_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="2" TDID="D2_C17_Estadao.txt.seg" TSENT="7">
		<RELATION TYPE="Overlap" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="2" TDID="D2_C17_Estadao.txt.seg" TSENT="10">
		<RELATION TYPE="Subsumption" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="4" TDID="D2_C17_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Subsumption" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="4" TDID="D2_C17_Estadao.txt.seg" TSENT="7">
		<RELATION TYPE="Subsumption" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="5" TDID="D2_C17_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="6" TDID="D2_C17_Estadao.txt.seg" TSENT="9">
		<RELATION TYPE="Overlap" JUDGE="Vinicius"/>
	</R>
	<R SDID="D2_C17_Estadao.txt.seg" SSENT="10" TDID="D1_C17_Folha.txt.seg" TSENT="6">
		<RELATION TYPE="Elaboration" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="7" TDID="D2_C17_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="7" TDID="D2_C17_Estadao.txt.seg" TSENT="11">
		<RELATION TYPE="Follow-up" JUDGE="Vinicius"/>
	</R>
	<R SDID="D2_C17_Estadao.txt.seg" SSENT="12" TDID="D1_C17_Folha.txt.seg" TSENT="7">
		<RELATION TYPE="Elaboration" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="9" TDID="D2_C17_Estadao.txt.seg" TSENT="12">
		<RELATION TYPE="Equivalence" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="10" TDID="D2_C17_Estadao.txt.seg" TSENT="16">
		<RELATION TYPE="Overlap" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="11" TDID="D2_C17_Estadao.txt.seg" TSENT="11">
		<RELATION TYPE="Follow-up" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="12" TDID="D2_C17_Estadao.txt.seg" TSENT="11">
		<RELATION TYPE="Follow-up" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="14" TDID="D2_C17_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="Vinicius"/>
	</R>
	<R SDID="D1_C17_Folha.txt.seg" SSENT="17" TDID="D2_C17_Estadao.txt.seg" TSENT="16">
		<RELATION TYPE="Overlap" JUDGE="Vinicius"/>
	</R>
	<R SDID="D2_C17_Estadao.txt.seg" SSENT="16" TDID="D1_C17_Folha.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="Vinicius"/>
	</R>
</Anotation>
